### ISSUE TITLE
Crowdin token is public

### ISSUE THREAD

**Issue by adelinn** [bcc-code/bcc-vote#236]
**User Story**
As a user, I want to have good translations, not broken or missing ones so that I can use the app easily and without bugs or security concerns.

**Additional Description**
Unauthorized people can exfiltrate text data from the system because it's accessible as a translation, or they can modify translations to piss us off, or they can poison the translations in the hope that they will find a potential **template injection** vulnerability in the system that can lead to **remote code execution**.

**Acceptance Criteria**
1. The token is accessible by our team members, but it's not publicly available.

Root cause: 38ea6d97611d89c1388eb8e96910381a350d2b32

**Comment by rvanoord** [comment]
@adelinn I would suggest putting tokens in deployment secrets (e.g. Github Secrets) so that they are not readily visible to anyone. If secrets have been exposed publicly, they should be rotated.

@philipdalen it may be an idea to set up a private repository to handle incidents (either support or security incidents). I.e. limit public tickets to features, bugs, improvements, and handle support incidents separately. Of course both repositories should count towards your metrics.

**Comment by comradekingu** [comment]
In the interest of arriving at good translations, why not opt to use Weblate instead of Crowdin?

**Comment by StevenMalaihollo** [comment]
Will archive this, as the repo is public
