### ISSUE TITLE
Issues for joining an active Polling event

### ISSUE THREAD

**Issue by StevenMalaihollo** [bcc-code/bcc-vote#320]
**Additional Description**
During Tønsbergs voting event on the evening of December the 13th, there was an issue where the administrator activated the event but members weren't able to click in to join the event. According to the admin the event was showing active like in the picture below, but there just wasn't any 'Delta' / 'Join' button.

In the end the admin sent the link out through telegram, which did work out. 

![image](https://user-images.githubusercontent.com/39584351/145960395-fb1f42fe-2fdc-4a7f-98fa-f08e6114b4e1.png)

**Acceptance Criteria**
1. Reproduced the issue that occured for Tønsberg.
2. Members waiting to join a polling event should always be able to click in on an event that is not Finished or Archived.

**Comment by rvanoord** [comment]
Users were instructed to go to Vote via the link in the topbar. Many went in before the vote was activated, but even after the vote was activated, refreshing the page did not make the "join" button appear.

**Comment by ameliebawolski** [comment]
as it is set up right now is that the delta button appears as soon as the event is create - "ikke aktive" and "aktive" status should therefore always show the delta button

**Comment by elpenny** [comment]
As it stands after the investigation no error was found in software. Problems for users (missing button) was due to admin error in setting up the vent - there was a role filter set to 'It Manager' role.

I would suggest adding a visible list of selected participant filters in the created event (probably for admin eyes only) so in case of error like this it would be easy to admin to spot it.
