### ISSUE TITLE
Vote - Poll events from arango DB

### ISSUE THREAD

**Issue by JakubC-projects** [bcc-code/bcc-vote#383]
![image](https://user-images.githubusercontent.com/39584351/174042806-c413eea2-8fdd-4bb8-b60b-269de36decc2.png)
_The problem and envisioned solution_

**Comment by StevenMalaihollo** [comment]
Previously it was thought to improve the server side with batching functionality. But this was not enough to handle a sudden burst in traffic because of:

- The long startup time caused the batching to be mistimed.
- Storing all previously batched answers caused for a large amount of state, which is discouraged in a serverless architecture.
- Arango could not handle a large amount of parallels connections caused by the batching.
